# Frankie Valli & the Four Seasons
# - Danger
# moddifed to fit the assingment (very difficult to come up with things to change)

def custom_song(mainnoun, name1, name2, girl, adj, adj2, verb):
    print("\n")
    print(f"{mainnoun}")
    print(f"{mainnoun}")
    print("\n")
    print(f"{mainnoun}")
    print(f"In each {adj} {noun2}")
    print(f"Why does {name1} always make me want {name2} so?")
    print("When you're still meeting him where lights are low")
    print(f"You vowed your love to me, but I know there {verb} be {mainnoun}")
    print(f"In each {adj2} {noun2}")
    print("\n")
    print("What happened to the girl I used to know?")
    print(f"The one {girl} that I loved and trusted so")
    print("Now when you walk with me")
    print(f"Each guy we pass {verb} be {mainnoun}, {mainnoun}")
    print("\n")
    print("Everyone knows (everyone knows)")
    print(f"It's him you {adj}")
    print("When are you gonna tell me?")
    print("\n")
    print("Oh, I can see (ooh, I can see)")
    print("Tears for me")
    print("'Cause me you were just teasin' ")
    print("His lips you were pleasin'")
    print("\n")
    print("You vowed your love to me")
    print(f"But I know there {verb} be {mainnoun}, {mainnoun}")
    print("You vowed your love to me")
    print(f"But I know there {verb} be {mainnoun}, {mainnoun}")
    print("\n")
    print("You vowed your love to me")
    print(f"But I know there {verb} be {mainnoun}, {mainnoun}")

name1 = input("Give me a name: ")
name2 = input("Give me another name: ")
girl = input("Give me a girl name: ")
mainnoun = input("Give me the main noun of the song: ")
adj = input("Give me an adjective: ")
adj2 = input("Give me an adjective: ")
verb = input("Give me a verb: ")
noun2 = input("Give me a noun: ")

custom_song(mainnoun, name1, name2, girl, adj, adj2, verb)




# the lyrics of the song before altered.
# def custom_song()
#     print("\n")
#     print("Danger")
#     print("Danger")
#     print("\n")
#     print("Danger")
#     print("In each passing stranger")
#     print(f"Why do you always make me want you so?")
#     print("When you're still meeting him where lights are low")
#     print("You vowed your love to me, but I know there could be danger")
#     print("In each passing stranger")
#     print("\n")
#     print("What happened to the girl I used to know?")
#     print("The one girl that I loved and trusted so")
#     print("Now when you walk with me")
#     print("Each guy we pass could be danger, danger")
#     print("\n")
#     print("Everyone knows (everyone knows)")
#     print("It's him you chose")
#     print("When are you gonna tell me?")
#     print("\n")
#     print("Oh, I can see (ooh, I can see)")
#     print("Tears for me")
#     print("'Cause me you were just teasin' ")
#     print("His lips you were pleasin'")
#     print("\n")
#     print("You vowed your love to me")
#     print("But I know there could be danger, danger")
#     print("You vowed your love to me")
#     print("But I know there could be danger, danger")
#     print("\n")
#     print("You vowed your love to me")
#     print("But I know there could be danger, danger")
